scalar DateTime
scalar Date

extend type TokenAuth {
	user: User
}

type Query {
	posts: [Post]!
	post(postId: String!): Post!
}

type Mutation {
	createPost(input: CreatePostInput!): Post!
	updatePost(input: UpdatePostInput!): Post!
	deletePost(postId: String!): Boolean!

	signupUser(input: SignupUserInput!): User!

	verifyToken(token: String!): VerifyToken
	refreshToken(token: String!): RefreshToken
	tokenAuth(email: String!, password: String!): TokenAuth
}

input SignupUserInput {
	email: String!
	password: String!
	firstName: String
	lastName: String
	dateOfBirth: DateTime
	zipCode: String
	students: [StudentInput]
}

input StudentInput {
	dateOfBirth: DateTime
	grade: String!
}

input UpdatePostInput {
	title: String
	truncatedBody: String
	body: String
	grade: String
	city: String
	state: String
	zipCode: String
}

input CreatePostInput {
	title: String!
	body: String!
	grade: String
	city: String
	state: String
	zipCode: String
	ups: Int
	downs: Int
	score: Int
}
