scalar DateTime
scalar Date

extend type TokenAuth {
	user: User
}

type Query {
	posts: [Post]!
	post(postId: String!): Post!
	comments(postId: String!) [Comment]!
	me: User!
}

type PostResult {
	post: Post!
	comments: [Comment!]
}

type Mutation {
	createPost(createPostInput: CreatePostInput!): Post!
	updatePost(updatePostInput: UpdatePostInput!): Post!
	deletePost(postId: String!): Boolean!

	signupUser(signupUserInput: SignupUserInput!): User!
	toggleLike(postId: Int!): Boolean!

	addComment(commentInput: CommentInput, postId: String!): Comment!
	removeComment(commentId: Int!): Boolean!
	updateComment(commentInput: CommentInput): Comment!

	updateUser(updateUserInput: UpdateUserInput): User!
	verifyToken(token: String!): VerifyToken
	refreshToken(token: String!): RefreshToken
	tokenAuth(email: String!, password: String!): TokenAuth
}

input CommentInput {
	body: String!
}

input UpdateUserInput {
	email: String
	firstName: String
	lastName: String
	dateOfBirth: DateTime
	zipCode: String
	students: [StudentInput]
}

input SignupUserInput {
	email: String!
	password: String!
	firstName: String
	lastName: String
	dateOfBirth: DateTime
	zipCode: String
	students: [StudentInput]
}

input StudentInput {
	dateOfBirth: DateTime
	grade: String!
}

input UpdatePostInput {
	title: String
	truncatedBody: String
	body: String
	grade: String
	city: String
	state: String
	zipCode: String
}

input CreatePostInput {
	title: String!
	body: String!
	grade: String
	city: String
	state: String
	zipCode: String
	ups: Int
	downs: Int
	score: Int
}
