type Post {
	id: ID!
	title: String!
	truncatedBody: String!
	body: String!
	grade: String
	zipCode: String
	createdAt: Date!
	updatedAt: Date!
	author: User!
}

type Comment {
	body: String!
	user: User!
	createdAt: Date!
}
