type Post {
	id: ID!
	title: String!
	truncatedBody: String!
	body: String!
	grade: String
	zipCode: String
	createdAt: Date!
	updatedAt: Date!
	author: User!
	# favorites: [User]
	favoriteCount: Int!
	naturalCreatedAt: String!
	commentCount: Int!
	postComments: [Comment]
}

type Comment {
	id: String!
	body: String!
	user: User!
	createdAt: Date!
	# likes: [User]
	likeCount: Int!
	naturalCreatedAt: String!
}
